redis:
  ## redis 单机环境配置
  host: 223.99.197.190
  port: 16379
  password: 123456@
  database: 14
  ssl: false

mysql:
  host: 223.99.197.190
  port: 13306
  database: qn_smart_home
  username: root
  password: Qn12345@